23기 백선호 ADD : kakao login
wecode-bootcamp-korea/23-2nd-GWAPANG-backend pull request #2
Opened 2021-08-20 05:52 UTC by preferbaik

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-20 08:07 UTC, kst6294 requested changes

2021-08-20 08:07 UTC, kst6294 commented on users/views.py
> +            token = jwt.encode({'id': user.id}, SECRET_KEY, algorithm='HS256')
algorithm 도 my_settings.py 에 추가해서 사용해주세요!

2021-08-20 08:07 UTC, kst6294 commented on users/views.py
> +                point             = random.randrange(10000, 1000000)
기본으로 포인트가 입력된다면, 
데이터베이스에 default 로 설정해보는건 어떤가요?

2021-08-20 08:07 UTC, kst6294 commented on users/views.py
> +            user, _ = User.objects.get_or_create(
get_or_create 로 분기한다면, 상태코드로 구분해주는건 어떤가요?
만약 추가정보를 받아야하는 경우를 고려할 수 있을 것 같아요

2021-08-20 11:33 UTC, preferbaik commented on users/views.py
> +            token = jwt.encode({'id': user.id}, SECRET_KEY, algorithm='HS256')
반영했습니다~~

2021-08-20 11:33 UTC, preferbaik commented on users/views.py
> +                point             = random.randrange(10000, 1000000)
반영했습니다~~

2021-08-20 11:33 UTC, preferbaik commented on users/views.py
> +            user, _ = User.objects.get_or_create(
반영했습니다~~

2021-08-21 01:26 UTC, kst6294 requested changes

2021-08-21 01:26 UTC, kst6294 commented on users/views.py
> +                point             = random.randrange(10000, 1000000)
view 도 반영해주세요~!

2021-08-22 06:24 UTC, kst6294 commented
LGTM 👍

2021-08-22 06:24 UTC, merged