23기 백선호 ADD: Upload Products
wecode-bootcamp-korea/23-2nd-GWAPANG-backend pull request #4
Opened 2021-08-20 12:32 UTC by preferbaik

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
상품의 등록을 구현했습니다.  form data로 data를 받았고 여러개의 사진을 s3에 저장했습니다. 첫번째로 들어온 사진을 썸네일 사진으로 저장했습니다. 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-21 01:47 UTC, kst6294 commented
통신결과 올려주시고 유닛테스트 진행해주세요!

2021-08-23 08:59 UTC, preferbaik commented
> 통신결과 올려주시고 유닛테스트 진행해주세요!

클래스 나눠서 먼저 올렸습니다!

2021-08-24 01:35 UTC, kst6294 requested changes
확인바랍니다!

2021-08-24 01:35 UTC, kst6294 commented on products/views.py
> +            return JsonResponse({"MESSAGE": "IMAGE_FILES_NONE"}, status=404)
images가 전달되지 않을 때 반환되는 값을 확인해보시고, images 의 bool 타입을 확인해보시면 좋겠습니다!

2021-08-24 01:35 UTC, kst6294 commented on products/models.py
> +    create_at        = models.DateField(auto_now=True)
datetimefield 로 선언해주세요
updated_at 도 추가해주시구요!

2021-08-24 01:35 UTC, kst6294 commented on products/views.py
> +            return JsonResponse({"MESSAGE": "YOU_CANT_UPLOAD"}, status=400)
오늘 날짜에 업로드가 이미 되어 있는 경우, 새로운 이미지의 업로드가 불가능 하다는 의미인거죠?
그리고 len 보다는 count() 의 사용은 어떤가요?

2021-08-24 01:35 UTC, kst6294 commented on products/views.py
> +                    is_thumbnail = True if index==0 else False
bulk_create 사용해서 먼저 이미지를 업데이트 하고, .first() 메소드를 사용해서 첫 이미지의 상태를 is_thumbnail 로 변경하는 방식은 어떤가요?

2021-08-24 09:49 UTC, kst6294 approved these changes

2021-08-24 09:49 UTC, kst6294 commented
conflict 해결해주세요!

2021-08-25 01:19 UTC, merged