23기 백선호 ADD : Post review & comment
wecode-bootcamp-korea/23-2nd-GWAPANG-backend pull request #5
Opened 2021-08-20 12:51 UTC by preferbaik

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
리뷰를 작성하고 review_id를 받을경우 리뷰에 댓글을 작성합니다. 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-21 01:48 UTC, kst6294 commented
통신결과 올려주시고
유닛테스트 진행해주세요!

2021-08-25 01:29 UTC, kst6294 requested changes

2021-08-25 01:29 UTC, kst6294 commented on reviews/views.py
> +            for review in reviews] if True else None
이부분에서 호출되는 sql 로그를 확인하고, 개선할 수 있는 방법이 있는지 확인해주세요!
orm 최적화 세션을 참고해보시면 좋겠습니다.

2021-08-25 02:49 UTC, preferbaik commented on reviews/views.py
> +            for review in reviews] if True else None
<img width="651" alt="스크린샷 2021-08-25 오전 11 40 45" src="https://user-images.githubusercontent.com/83463559/130718177-24fc73dd-96c1-4d2d-b327-c8183f51cc2b.png">
<img width="631" alt="스크린샷 2021-08-25 오전 11 26 13" src="https://user-images.githubusercontent.com/83463559/130718198-4f62342f-31c2-402c-a64e-4b2ffa23afcd.png">
감사합니다! Query수 줄였습니다~

2021-08-25 07:07 UTC, kst6294 approved these changes

2021-08-25 07:07 UTC, merged